import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.49.1";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const RENDER="https://unipool-backend-owb9.onrender.com";
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,content-type,apikey,x-client-info","Access-Control-Allow-Methods":"GET,POST,PATCH,DELETE,OPTIONS"};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,"Content-Type":"application/json"}});const F=(d:string,s=400)=>J({detail:d},s);const now=()=>new Date().toISOString();
async function hash(v:string){const b=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)));return[...b].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function rf(path:string,token:string){try{const c=new AbortController();const t=setTimeout(()=>c.abort(),8000);const r=await fetch(`${RENDER}${path}`,{headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},signal:c.signal,cache:"no-store"});clearTimeout(t);return r}catch{return null}}
async function auth(req:Request){const h=req.headers.get("authorization")||"";if(!h.toLowerCase().startsWith("bearer "))throw{status:401,detail:"Missing session"};const token=h.slice(7).trim(),th=await hash(token);const{data:c}=await db.from("unipool_session_cache").select("*").eq("token_hash",th).maybeSingle();let u:any=null;if(c&&new Date(c.expires_at).getTime()>Date.now())u={user_id:c.user_id,name:c.user_name||"Student",email:c.user_email||null,picture:c.user_picture||null,token};else{const r=await rf("/api/auth/me",token);if(!r?.ok)throw{status:r?.status===401?401:503,detail:r?.status===401?"Session expired":"Session verification unavailable"};const d=await r.json();u={...d,token};await db.from("unipool_session_cache").upsert({token_hash:th,user_id:d.user_id,user_name:d.name||"Student",user_email:d.email||null,user_picture:d.picture||null,expires_at:new Date(Date.now()+30*60e3).toISOString(),validated_at:now()})}await db.from("unipool_user_directory").upsert({user_id:u.user_id,name:u.name||"Student",email:u.email||null,picture:u.picture||null,...(c&&new Date(c.expires_at).getTime()>Date.now()?{}:{username:u.username||null,school_name:u.school_name||null,branch_name:u.branch_name||null,batch_year:u.batch_year||null,college_verified:Boolean(u.college_verified)}),updated_at:now()});return u}
async function b(req:Request){try{return await req.json()}catch{return{}}}
function adminGuard(u:any){if(String(u?.email||"").toLowerCase()!=="utkarsh7023340530@gmail.com"&&!u?.is_admin)throw{status:403,detail:"Admin access required"}}
async function syncSearch(q:string,u:any){const r=await rf(`/api/search/global?q=${encodeURIComponent(q)}`,u.token);if(!r?.ok)return;const d=await r.json().catch(()=>null);for(const p of d?.people||[]){if(!p?.user_id)continue;await db.from("unipool_user_directory").upsert({user_id:p.user_id,name:p.name||"Student",email:p.email||null,picture:p.picture||null,username:p.username||null,school_name:p.school_name||null,branch_name:p.branch_name||null,batch_year:p.batch_year||null,college_verified:Boolean(p.college_verified),updated_at:now()})}}
async function trustMap(ids:string[]){const out=new Map<string,any>();if(!ids.length)return out;const{data}=await db.from("unipool_trip_feedback").select("rated_user_id,punctuality,coordination,behaviour").in("rated_user_id",ids);const bucket=new Map<string,any[]>();for(const r of data||[]){const a=bucket.get(r.rated_user_id)||[];a.push(r);bucket.set(r.rated_user_id,a)}for(const id of ids){const rows=bucket.get(id)||[];if(!rows.length){out.set(id,{count:0,overall:null});continue}const avg=(k:string)=>rows.reduce((n:number,r:any)=>n+Number(r[k]||0),0)/rows.length;out.set(id,{count:rows.length,punctuality:Number(avg("punctuality").toFixed(2)),coordination:Number(avg("coordination").toFixed(2)),behaviour:Number(avg("behaviour").toFixed(2)),overall:Number(((avg("punctuality")+avg("coordination")+avg("behaviour"))/3).toFixed(2))})}return out}
async function eventRows(userId:string){const{data:events}=await db.from("unipool_campus_events").select("*").eq("active",true).gte("starts_at",new Date(Date.now()-24*3600e3).toISOString()).order("starts_at").limit(20);const ids=(events||[]).map((e:any)=>e.id);if(!ids.length)return[];const{data:rsvps}=await db.from("unipool_campus_event_rsvps").select("event_id,user_id,status").in("event_id",ids);const counts=new Map<string,{going:number;interested:number}>();for(const r of rsvps||[]){const x=counts.get(r.event_id)||{going:0,interested:0};if(r.status==="going")x.going++;else x.interested++;counts.set(r.event_id,x)}return(events||[]).map((e:any)=>({...e,counts:counts.get(e.id)||{going:0,interested:0},my_rsvp:(rsvps||[]).find((r:any)=>r.event_id===e.id&&r.user_id===userId)?.status||null}))}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:C});const url=new URL(req.url);const path=url.pathname.split("/unipool-people")[1]||"/";try{if(path==="/health")return J({status:"ok",version:"people-2.0"});const u=await auth(req);
if(path==="/admin/people"&&req.method==="GET"){adminGuard(u);const{data,error}=await db.from("unipool_user_directory").select("user_id,name,email,username,picture,school_name,branch_name,batch_year,college_verified,updated_at").order("name",{ascending:true}).limit(2000);if(error)throw error;return J(data||[])}
if(path==="/admin/stats"&&req.method==="GET"){adminGuard(u);const{count,error}=await db.from("unipool_user_directory").select("user_id",{count:"exact",head:true});if(error)throw error;return J({total_users:count||0,open_pools:0,closed_pools:0})}
if(path==="/admin/pools"&&req.method==="GET"){adminGuard(u);return J([])}
if(path==="/onboarding"&&req.method==="GET"){const{data,error}=await db.from("unipool_user_directory").select("tour_completed_at").eq("user_id",u.user_id).maybeSingle();if(error)throw error;return J({completed:Boolean(data?.tour_completed_at)})}
if(path==="/onboarding"&&req.method==="POST"){const{error}=await db.from("unipool_user_directory").update({tour_completed_at:now()}).eq("user_id",u.user_id);if(error)throw error;return J({completed:true})}
const pm=path.match(/^\/profiles\/([^/]+)$/);if(pm&&req.method==="GET"){const id=decodeURIComponent(pm[1]);const{data,error}=await db.from("unipool_user_directory").select("user_id,name,picture,username,school_name,branch_name,batch_year,college_verified").eq("user_id",id).maybeSingle();if(error)throw error;if(!data)return F("User not found",404);return J(data)}
if(path==="/search"&&req.method==="GET"){const q=(url.searchParams.get("q")||"").trim();if(q.length<2)return J([]);await syncSearch(q,u);const safe=q.replace(/[%_,]/g,"");const filters=[`name.ilike.%${safe}%`,`email.ilike.%${safe}%`,`username.ilike.%${safe}%`,`school_name.ilike.%${safe}%`,`branch_name.ilike.%${safe}%`];let{data}=await db.from("unipool_user_directory").select("user_id,name,email,picture,username,school_name,branch_name,batch_year,college_verified").or(filters.join(",")).neq("user_id",u.user_id).limit(30);if(/^\d{4}$/.test(q)){const{data:batch}=await db.from("unipool_user_directory").select("user_id,name,email,picture,username,school_name,branch_name,batch_year,college_verified").eq("batch_year",Number(q)).neq("user_id",u.user_id).limit(30);const map=new Map((data||[]).map((x:any)=>[x.user_id,x]));for(const x of batch||[])map.set(x.user_id,x);data=[...map.values()].slice(0,30)}const ids=(data||[]).map((x:any)=>x.user_id);const[{data:saved},trust]=await Promise.all([db.from("unipool_saved_people").select("target_user_id").eq("owner_user_id",u.user_id),trustMap(ids)]);const set=new Set((saved||[]).map((x:any)=>x.target_user_id));return J((data||[]).map((x:any)=>({...x,saved:set.has(x.user_id),trust:trust.get(x.user_id)||{count:0,overall:null}})))}
if(path==="/saved"&&req.method==="GET"){const{data:s}=await db.from("unipool_saved_people").select("target_user_id,created_at").eq("owner_user_id",u.user_id).order("created_at",{ascending:false});const ids=(s||[]).map((x:any)=>x.target_user_id);if(!ids.length)return J([]);const[{data:p},trust]=await Promise.all([db.from("unipool_user_directory").select("*").in("user_id",ids),trustMap(ids)]);const m=new Map((p||[]).map((x:any)=>[x.user_id,x]));return J(ids.map((id:string)=>m.get(id)?{...m.get(id),trust:trust.get(id)||{count:0,overall:null}}:null).filter(Boolean))}
const sm=path.match(/^\/saved\/([^/]+)$/);if(sm&&req.method==="POST"){await db.from("unipool_saved_people").upsert({owner_user_id:u.user_id,target_user_id:sm[1]});return J({ok:true})}if(sm&&req.method==="DELETE"){await db.from("unipool_saved_people").delete().eq("owner_user_id",u.user_id).eq("target_user_id",sm[1]);return J({ok:true})}
if(path==="/trusted-contacts"&&req.method==="GET"){const{data}=await db.from("unipool_trusted_contacts").select("*").eq("user_id",u.user_id).order("created_at");return J(data||[])}if(path==="/trusted-contacts"&&req.method==="POST"){const x=await b(req);if(!String(x.name||"").trim()||(!x.email&&!x.phone))return F("Add a name and an email or phone");const{data,error}=await db.from("unipool_trusted_contacts").insert({user_id:u.user_id,name:String(x.name).trim(),email:x.email||null,phone:x.phone||null,updated_at:now()}).select("*").single();if(error)throw error;return J(data)}const cm=path.match(/^\/trusted-contacts\/([^/]+)$/);if(cm&&req.method==="DELETE"){await db.from("unipool_trusted_contacts").delete().eq("id",cm[1]).eq("user_id",u.user_id);return J({ok:true})}
if(path==="/notifications"&&req.method==="GET"){const lim=Math.min(100,Number(url.searchParams.get("limit")||50));const type=url.searchParams.get("type");let q=db.from("unipool_v3_notifications").select("*").eq("user_id",u.user_id).order("created_at",{ascending:false}).limit(lim);if(type)q=q.eq("type",type);const{data}=await q;return J(data||[])}const nm=path.match(/^\/notifications\/([^/]+)\/read$/);if(nm&&req.method==="PATCH"){await db.from("unipool_v3_notifications").update({read_at:now()}).eq("id",nm[1]).eq("user_id",u.user_id);return J({ok:true})}if(path==="/notifications/read-all"&&req.method==="POST"){await db.from("unipool_v3_notifications").update({read_at:now()}).eq("user_id",u.user_id).is("read_at",null);return J({ok:true})}
if(path==="/campus-events"&&req.method==="GET")return J(await eventRows(u.user_id));const em=path.match(/^\/campus-events\/([^/]+)\/rsvp$/);if(em&&req.method==="POST"){const x=await b(req),status=String(x.status||"");if(!["going","interested"].includes(status))return F("Choose going or interested");const{data:e}=await db.from("unipool_campus_events").select("id,title").eq("id",em[1]).eq("active",true).maybeSingle();if(!e)return F("Event not found",404);await db.from("unipool_campus_event_rsvps").upsert({event_id:e.id,user_id:u.user_id,status,updated_at:now()},{onConflict:"event_id,user_id"});return J({ok:true,status})}if(em&&req.method==="DELETE"){await db.from("unipool_campus_event_rsvps").delete().eq("event_id",em[1]).eq("user_id",u.user_id);return J({ok:true})}
if(path==="/campus-home"&&req.method==="GET"){const month=new Date().toISOString().slice(0,7),start=new Date(`${month}-01T00:00:00Z`),end=new Date(start);end.setUTCMonth(end.getUTCMonth()+1);const[{count:saved},{count:contacts},{count:unread},{data:gp},{count:circles},{count:watches},{data:tx},events]=await Promise.all([db.from("unipool_saved_people").select("target_user_id",{count:"exact",head:true}).eq("owner_user_id",u.user_id),db.from("unipool_trusted_contacts").select("id",{count:"exact",head:true}).eq("user_id",u.user_id),db.from("unipool_v3_notifications").select("id",{count:"exact",head:true}).eq("user_id",u.user_id).is("read_at",null),db.from("unipool_game_progress").select("xp").eq("user_id",u.user_id),db.from("unipool_circle_members").select("circle_id",{count:"exact",head:true}).eq("user_id",u.user_id),db.from("unipool_route_watches").select("id",{count:"exact",head:true}).eq("user_id",u.user_id).eq("active",true),db.from("unipool_personal_transactions").select("kind,amount_paise").eq("user_id",u.user_id).is("deleted_at",null).gte("occurred_at",start.toISOString()).lt("occurred_at",end.toISOString()),eventRows(u.user_id)]);const xp=(gp||[]).reduce((n:number,x:any)=>n+Number(x.xp||0),0);let income=0,expense=0;for(const r of tx||[]){if(r.kind==="income")income+=Number(r.amount_paise||0);else expense+=Number(r.amount_paise||0)}return J({saved_people:saved||0,trusted_contacts:contacts||0,unread_notifications:unread||0,total_xp:xp,level:Math.floor(xp/250)+1,circles:circles||0,saved_routes:watches||0,month,income_paise:income,expense_paise:expense,net_cashflow_paise:income-expense,events:(events||[]).slice(0,4)})}
return F("Not Found",404)}catch(e:any){console.error(e);return F(e?.detail||e?.message||"Unexpected error",Number(e?.status||500))}});

